"""empty message

Revision ID: ec5397b26dae
Revises: 86b96468cd5b
Create Date: 2021-04-10 18:26:14.260527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5397b26dae'
down_revision = '86b96468cd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hash_code')
    # ### end Alembic commands ###
